'use strict';
  const financeReports = {
    revenue: { title: '本月營收', en: 'Revenue Overview', subtitle: '掌握本月營收表現，分析成長趨勢、BU 與產品貢獻，並與預算及去年同期比較。', metrics: [['本月營收','Total Revenue','USD 1.25M','↑ 5%','blue'],['上月營收','Last Month','USD 1.19M','較上月 (Aug)','purple'],['去年同期','Same Period Last Year','USD 1.05M','↑ 19%','teal'],['年度目標達成率','YTD Budget Achievement','68%','YTD 營收 USD 9.8M','pink']], chart: '營收趨勢', chartEn: 'Revenue Trend', pie: '營收構成', pieEn: 'Revenue Breakdown', table: 'BU 營收排名', tableEn: 'Revenue by BU', values: [130,125,155,175,188,182,200,230,228,240,255,285], segments: [['BU-A',28],['BU-B',24],['BU-C',18],['BU-D',16],['BU-E',10],['其他',4]], insight: ['本月營收較上月成長 5%，主要來自 BU-A 與 BU-C 的營收增加。','累計營收達成年度預算 68%，進度符合預期。','Product A 持續保持最高營收貢獻。'] },
    cash: { title: '可用現金', en: 'Cash / Liquidity Overview', subtitle: '掌握整體現金部位、流動性狀況、銀行帳戶餘額、資金調度與現金預測。', metrics: [['可用現金總額','Available Cash Balance','USD 320M','↑ 12%','green'],['銀行帳戶餘額','Bank Account Balance','USD 305M','↑ 10%','blue'],['近期資金調度','Net Cash Flow (30D)','USD 45M','↑ 25%','purple'],['流動性覆蓋率','Liquidity Coverage Ratio','2.8x','高於內部門檻 1.5x','orange']], chart: '現金部位趨勢', chartEn: 'Cash Position Trend', pie: '現金結構', pieEn: 'Cash Composition', table: '銀行帳戶餘額', tableEn: 'Bank Account Balance', values: [315,312,345,336,382,375,370,385,410,412,416,445], segments: [['營運帳戶',55],['定存／短投',20],['受限現金',15],['其他',10]], insight: ['可用現金較上月增加 12%，主要來自客戶回款與營運資金改善。','流動性覆蓋率 2.8x，高於內部門檻 1.5x。','未來 4 週預期淨現金流為正。'] },
    pnl: { title: '本月損益', en: 'P&L Overview', subtitle: '掌握本月損益表現，分析收入、成本、費用與淨利，快速了解營運狀況。', metrics: [['營業收入','Revenue','USD 45M','↑ 8%','blue'],['營業成本','Cost of Revenue','USD 28M','↑ 5%','purple'],['營業毛利','Gross Profit','USD 17M','↑ 14%','teal'],['營業費用','Operating Expense','USD 12M','↑ 6%','orange'],['本月淨利','Net Profit','USD 5M','↑ 27%','purple']], chart: '損益趨勢', chartEn: 'P&L Trend', pie: '損益結構', pieEn: 'P&L Composition', table: '損益表（本月）', tableEn: 'P&L Statement (This Month)', values: [46,48,55,50,59,62,65,68,75,76,78,82], segments: [['營業成本',62],['營業費用',27],['營業毛利',9],['其他',2]], insight: ['本月淨利較上月增加 27%，主要來自營業收入成長與毛利率提升。','BU-A 為本月獲利最高單位。','營業費用增加 6%，仍在預算範圍內。'] },
    budget: { title: '年度預算', en: 'Budget Execution', subtitle: '掌握年度預算達成率，分析各 BU／科目執行狀況，追蹤差異原因並預測全年結算結果。', metrics: [['年度預算總額','Total Budget','USD 480M','較去年 +8%','pink'],['已執行金額','YTD Actual','USD 320M','達成率 67%','blue'],['預算剩餘','Remaining Budget','USD 160M','33%','blue'],['預測全年執行','Full Year Forecast','USD 470M','預測達成率 98%','green'],['預算差異(絕對值)','Variance','USD -10M','-2% 低於預算','red']], chart: '月度預算執行趨勢', chartEn: 'Budget vs Actual Trend', pie: '預算達成率（依 BU）', pieEn: 'Budget Achievement by BU', table: '科目預算執行', tableEn: 'Budget Execution by Account', values: [45,47,51,53,52,55,57,63,66,68,70,72], segments: [['BU-A',26],['BU-B',23],['BU-C',20],['BU-D',16],['BU-E',15]], insight: ['目前預測全年達成率 98%，整體可望接近預算目標。','BU-C、BU-D 與 BU-E 達成率偏低。','營業費用成長率低於預期。'] },
    bu: { title: 'BU 表現分析', en: 'BU Performance Analysis', subtitle: '深入分析各業務單位的營收、獲利、預算達成與成長表現，協助掌握 BU 營運狀況。', metrics: [['BU 總營收','Total BU Revenue','USD 1.25B','↑ 12%','blue'],['平均獲利率','Average Profit Margin','18%','+3%','purple'],['表現最佳 BU','Top Performing BU','BU-A','USD 480M 營收','orange'],['表現未達預算 BU 數','Underperforming BU Count','2 項','占全部 BU 33%','red'],['預算達成率','Budget Attainment','92%','↑ +4%','green']], chart: 'BU 營收與獲利表現', chartEn: 'BU Revenue & Profit Performance', pie: 'BU 營收貢獻佔比', pieEn: 'Revenue Contribution by BU', table: 'BU 詳細表現', tableEn: 'BU Performance Details', values: [480,280,200,120,100,70], segments: [['BU-A',38],['BU-B',22],['BU-C',16],['BU-D',10],['BU-E',8],['其他',6]], insight: ['BU-A 持續領先，營收 USD 480M，佔總營收 38%。','BU-D 獲利率承壓。','2 個 BU 低於預算，需擬定改善計畫。'] },
    alerts: { title: '重大異常／預警', en: 'Major Exceptions & Alerts', subtitle: '整合關鍵業務、財務與營運異常，協助快速識別風險並追蹤處理進度。', metrics: [['開啟異常','Open Alerts','32 項','↓ 20%','red'],['高風險','High Risk','8 項','↓ 11%','red'],['今日到期','Due Today','6 項','↑ 50%','blue'],['逾期未處理','Overdue','12 項','↓ 25%','orange'],['已升級','Escalated','4 項','↑ 33%','purple']], chart: '異常數量趨勢', chartEn: 'Alert Trend', pie: '異常類型分佈', pieEn: 'Alerts by Category', table: '重大異常清單', tableEn: 'Alert List', values: [14,16,15,18,19,21,23,27,24,28,30,32], segments: [['營收異常',25],['成本異常',22],['現金流',19],['預算執行',12],['營運異常',12],['其他',10]], insight: ['營收與毛利異常佔比最高，需關注市場需求及定價策略。','逾期未處理件數較上月下降 25%。','合規風險有所上升，需加強審核流程。'] }
  };
