'use strict';
  function miniLine(color = '#1b76ff') { return `<svg class="mini-line" viewBox="0 0 120 52" aria-hidden="true"><polyline points="0,42 16,29 30,38 46,23 63,27 78,14 95,20 120,2" fill="none" stroke="${color}" stroke-width="2"/><path d="M0 42 16 29 30 38 46 23 63 27 78 14 95 20 120 2v50H0z" fill="${color}" opacity=".08"/></svg>`; }
  function financeMetrics(items) { return `<div class="finance-metrics ${items.length === 5 ? 'five' : ''}">${items.map(([label,en,value,change,color]) => `<section class="finance-metric"><div class="finance-metric-head"><span class="finance-metric-icon ${color}">${icon(color === 'red' ? 'info' : color === 'green' ? 'check' : 'report')}</span><span><strong>${label}</strong><small>${en}</small></span></div><b class="${color === 'red' ? 'negative' : ''}">${value}</b><div class="finance-metric-foot"><strong class="${color === 'red' ? 'negative' : 'positive'}">${change}</strong>${miniLine(color === 'red' ? '#ff5964' : color === 'purple' ? '#9541ff' : color === 'teal' || color === 'green' ? '#00c3a2' : '#1b76ff')}</div></section>`).join('')}</div>`; }
  function financeChart(values) {
    const max = Math.max(...values) * 1.12;
    return `<div class="finance-chart"><div class="chart-grid"><span>300</span><span>200</span><span>100</span><span>0</span></div><div class="chart-bars">${values.map((value,index) => `<div class="chart-column"><span class="chart-bar" style="height:${Math.max(8, value / max * 100)}%"></span><small>${index + 1}月</small></div>`).join('')}</div></div>`;
  }
  function financeDonut(segments, center) {
    const colors = ['#2178ff','#5da8ff','#19bfda','#69d9a6','#8b63f7','#ff9d4b','#ff6b83'];
    let offset = 0;
    const stops = segments.map(([,percent], index) => { const start = offset; offset += percent; return `${colors[index % colors.length]} ${start}% ${offset}%`; }).join(',');
    return `<div class="donut-layout"><div class="donut" style="background:conic-gradient(${stops})"><div><strong>${center}</strong><small>示範數據</small></div></div><div class="donut-legend">${segments.map(([label,percent], index) => `<div><i style="background:${colors[index % colors.length]}"></i><span>${label}</span><strong>${percent}%</strong></div>`).join('')}</div></div>`;
  }
  function financeTable(key) {
    const rows = key === 'alerts' ? [['營收異常','BU-A','9月營收較預期低 22%','嚴重'],['成本異常','BU-B','行銷費用超出預算 35%','高'],['現金流','BU-C','應收帳款逾期金額上升','高'],['預算執行','BU-D','Q3 預算執行率偏低','中']] : [['BU-A','480M','38%','↑ 18%'],['BU-B','280M','22%','↑ 12%'],['BU-C','200M','16%','↑ 8%'],['BU-D','120M','10%','↓ 5%'],['BU-E','100M','8%','↑ 6%'],['其他','70M','6%','↑ 10%']];
    return `<div class="table-scroll"><table class="finance-table"><thead><tr><th>#</th><th>${key === 'alerts' ? '類型' : 'BU'}</th><th>${key === 'alerts' ? '單位／BU' : '本月金額 (USD)'}</th><th>${key === 'alerts' ? '事件' : '佔比'}</th><th>${key === 'alerts' ? '等級' : '較上月'}</th></tr></thead><tbody>${rows.map((row,index) => `<tr><td>${index + 1}</td>${row.map(value => `<td>${value}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
  }
  function financeReportPage(key) {
    const report = financeReports[key];
    return `<div class="finance-report"><div class="finance-report-top"><button type="button" class="back-link" data-page="reports">← 返回總覽</button><span>最後更新：2026/09/30 09:30 (UTC+8)</span></div><div class="finance-report-heading"><div><h1>${report.title} <span>${report.en}</span></h1><p>${report.subtitle}</p></div><div class="finance-controls"><label>期間<select><option>本月 (2026/09)</option><option>上月 (2026/08)</option></select></label><label>幣別<select><option>USD</option><option>TWD (NT$)</option></select></label><label>範圍<select><option>全部 BU</option><option>BU-A</option><option>BU-B</option></select></label><button type="button" class="button button-primary" data-finance-filter>⚲ 進階篩選</button></div></div>
      ${financeMetrics(report.metrics)}<div class="finance-report-grid"><section class="finance-panel chart-panel"><h2>${report.chart} <small>${report.chartEn}</small></h2><div class="chart-legend"><span>● 本年</span><span>● 去年</span><span>● 預算</span></div>${financeChart(report.values)}</section><section class="finance-panel donut-panel"><h2>${report.pie} <small>${report.pieEn}</small></h2>${financeDonut(report.segments, report.metrics[0][2])}</section></div>
      <div class="finance-report-grid lower"><section class="finance-panel"><h2>${report.table} <small>${report.tableEn}</small></h2>${financeTable(key)}</section><section class="finance-panel insights"><h2>關鍵洞察 <small>Key Insights</small></h2>${report.insight.map((text,index) => `<div class="insight"><span class="insight-icon ${['green','blue','purple'][index]}">${icon(index === 0 ? 'arrow' : index === 1 ? 'report' : 'info')}</span><p>${text}</p></div>`).join('')}</section></div></div>`;
  }
  function financeOverviewPage() {
    return `<div class="finance-report"><div class="finance-report-top"><span>財務工作空間</span><span>最後更新：2026/09/30 09:30 (UTC+8)</span></div><div class="finance-report-heading"><div><h1>財務總覽 <span>Finance Overview</span></h1><p>集中掌握營收、現金、損益、預算與 BU 表現。</p></div></div>${financeMetrics([financeReports.revenue.metrics[0],financeReports.cash.metrics[0],financeReports.pnl.metrics[4],financeReports.alerts.metrics[0]])}<div class="finance-overview-grid">${[['revenue','本月營收','檢視營收趨勢與 BU 貢獻'],['cash','可用現金','掌握現金部位與流動性'],['pnl','本月損益','檢視營運損益表現'],['budget','年度預算','追蹤預算執行與差異'],['bu','BU 表現分析','分析業務單位表現'],['alerts','重大異常','追蹤重要風險與預警']].map(([page,title,subtitle]) => `<button type="button" data-page="${page}" class="finance-overview-link"><span class="list-icon">${icon(({revenue:'users',cash:'clock',pnl:'report',budget:'track',bu:'home',alerts:'info'})[page])}</span><span><strong>${title}</strong><small>${subtitle}</small></span>${icon('chevron')}</button>`).join('')}</div></div>`;
  }
  function financeLandingPage() { return financeOverviewPage(); }
  function financeDataCenterPage() { return `${pageTitle('DATA CENTER', '資料中心', '集中檢視財務政策、作業指引與示範資料。')}${card(`<div class="section-title"><h2>政策與指引</h2></div>${referencePolicyTiles()}`, 'reference-card')}`; }
  const pages = { employee: { home: referenceEmployeeHome, policy: referencePolicyPage, service: referenceServicePage, applications: referenceTrackPage, faq: faqPage }, finance: { home: financeLandingPage, reports: financeOverviewPage, revenue: () => financeReportPage('revenue'), cash: () => financeReportPage('cash'), pnl: () => financeReportPage('pnl'), budget: () => financeReportPage('budget'), bu: () => financeReportPage('bu'), alerts: () => financeReportPage('alerts'), review: reviewPage, policy: financeDataCenterPage } };
