'use strict';
  function referenceEmployeeHome() {
    const applications = loadApplications();
    return `<div class="home-reference-grid"><div class="home-primary">
      ${employeeBanner('早安，Evren', '歡迎使用 Finance SSC，一站式財務共享服務平台', '快速申請・查詢進度・遵循規範・取得協助')}
      ${card(`<div class="section-title"><div><h2>常用服務</h2><span>申請各項財務服務，提升工作效率</span></div><button class="link-action" data-page="service">查看所有服務 ${icon('chevron')}</button></div>${referenceServiceTiles()}`, 'reference-card home-services')}
      ${card(`<div class="section-title"><div><h2>我的申請</h2><span>追蹤申請進度與處理狀況</span></div><button class="link-action" data-page="applications">查看全部 ${icon('chevron')}</button></div><div class="home-status-grid">${[['進行中', 2, 'blue', 'clock'], ['已完成', 8, 'green', 'check'], ['需補件', 1, 'red', 'info'], ['已取消', 0, 'gray', 'policy']].map(([label, count, color, ico]) => `<div class="home-status ${color}"><span>${icon(ico)}</span><div><strong>${label}</strong><b>${count} <small>件</small></b></div></div>`).join('')}</div>${referenceApplicationTable(applications.slice(0, 4), true)}`, 'reference-card home-applications')}
    </div><div class="home-secondary">${card(`<div class="section-title"><h2>通知與公告</h2><button class="link-action" data-page="policy">全部 ${icon('chevron')}</button></div><div class="announcement-list">${[['9/30 財務報銷截止提醒', '請於 9/30 前完成報銷申請', '2026/09/25', 'red', 'info'], ['出差政策更新', '新增國外出差申請流程', '2026/09/20', 'blue', 'policy'], ['系統維護公告', 'Helios 系統 10/3 02:00–06:00 維護', '2026/09/18', 'red', 'bell']].map(([title, detail, date, color, ico]) => `<div class="announcement"><span class="tile-icon ${color}">${icon(ico)}</span><span><strong>${title}</strong><small>${detail}</small></span><time>${date}</time></div>`).join('')}</div>`, 'reference-card announcements')}
      ${card(`<div class="section-title"><div class="assistant-title-icon">${icon('ask')}</div><div><h2>AI 助手</h2><span>有問題？我來協助您</span></div><button class="link-action" data-page="faq">開啟對話 ${icon('chevron')}</button></div><div class="question-list">${['如何申請報銷？', '出差申請需要準備哪些文件？', '付款申請的流程是？', '公司報銷規範有哪些？', '我可以查詢申請進度嗎？'].map(question => `<button type="button" data-question="${question}"><span>○</span>${question}${icon('chevron')}</button>`).join('')}</div>`, 'reference-card home-assistant')}</div></div>
    ${card(`<div class="section-title"><div><h2>財務政策與規範</h2><span>各項財務管理制度與操作指引</span></div><button class="link-action" data-page="policy">查看全部 ${icon('chevron')}</button></div>${referencePolicyTiles()}`, 'reference-card home-policy')}`;
  }
  function referenceApplicationTable(rows, home = false) {
    return `<div class="table-scroll"><table class="reference-table"><thead><tr><th>申請單號</th><th>${home ? '申請類型' : '申請項目'}</th>${home ? '' : '<th>申請目的</th>'}<th>申請日期</th>${home ? '<th>金額</th>' : ''}<th>狀態</th>${home ? '' : '<th>預計完成日</th>'}<th>操作</th></tr></thead><tbody>${rows.map(item => `<tr><td class="reference-id">${escapeHtml(item.id)}</td><td>${escapeHtml(home ? (item.type === '機票費' || item.type === '住宿費' ? '出差申請' : item.type === '廠商付款' ? '付款申請' : '報銷申請') : item.type)}</td>${home ? '' : `<td>${escapeHtml(item.title)}</td>`}<td>${escapeHtml(item.date)}</td>${home ? `<td>${escapeHtml(item.amount)}</td>` : ''}<td>${badge(item.status)}</td>${home ? '' : `<td>${item.status === '已取消' ? '－' : '2026/10/08'}</td>`}<td><button class="row-link" type="button" data-application="${escapeHtml(item.id)}">${home ? '查看' : '查看詳情'} ${home ? '' : icon('chevron')}</button></td></tr>`).join('')}</tbody></table></div>`;
  }
  function referencePolicyPage() {
    const visible = policies.filter(item => `${item.title} ${item.text}`.includes(state.search));
    const tabContent = state.policyTab === 'sop' ? { title: '熱門作業指引', tiles: referencePolicyTiles([['報銷作業流程','送件與補件步驟','green','receipt'],['出差申請教學','申請與核准流程','blue','plane'],['付款審核流程','付款資料與附件','orange','credit'],['憑證上傳指引','系統操作步驟','purple','book']]) } : state.policyTab === 'training' ? { title: '熱門教育訓練', tiles: referencePolicyTiles([['報銷制度課程','費用規範入門','green','receipt'],['出差制度說明','差旅補助與申請','blue','plane'],['付款申請教學','廠商付款流程','orange','credit'],['Helios 操作教學','系統操作影片','purple','book']]) } : { title: '熱門主題', tiles: referencePolicyTiles() };
    return `${employeeBanner('懂規定', '申請前先了解各項財務政策、作業規範與操作教學，讓您的申請更順利、更符合規定。')}
      ${card(`<div class="policy-tabs"><button class="${state.policyTab === 'policy' ? 'selected' : ''}" type="button" data-policy-tab="policy">${icon('policy')}政策規範</button><button class="${state.policyTab === 'sop' ? 'selected' : ''}" type="button" data-policy-tab="sop">${icon('track')}作業指引 (SOP)</button><button class="${state.policyTab === 'training' ? 'selected' : ''}" type="button" data-policy-tab="training">${icon('book')}教育訓練</button></div><div class="policy-toolbar"><label class="reference-search">${icon('search')}<input id="content-search" type="search" value="${escapeHtml(state.search)}" placeholder="搜尋政策、SOP 或教學內容…（例如：報銷規範、出差申請、付款流程）"></label><label>主題類別<select><option>全部類別</option><option>費用與報銷</option><option>付款與採購</option></select></label><label>適用對象<select><option>全部對象</option><option>一般員工</option><option>財務人員</option></select></label><label>文件類型<select><option>全部類型</option><option>政策</option><option>SOP</option></select></label></div>`, 'reference-card policy-controls')}
      ${card(`<div class="section-title stacked"><div><h2>${tabContent.title}</h2><span>常用的財務政策與作業指引，協助您快速找到所需資訊。</span></div></div>${tabContent.tiles}`, 'reference-card policy-topics')}
      <div class="policy-bottom-grid">${card(`<div class="section-title stacked"><div><h2>最新發布</h2><span>掌握最新的政策公告、規範更新與重要資訊。</span></div><button class="link-action">查看全部 ${icon('chevron')}</button></div><div class="release-list">${(visible.length ? visible : policies).map((item, index) => `<button type="button" data-release="${index}"><span class="tile-icon ${['red','blue','green','purple'][index]}">${icon(index === 0 ? 'bell' : 'policy')}</span><span><strong>${['差旅費報銷標準調整公告','出差申請流程更新','發票憑證審核原則','Helios 系統操作教學上線'][index]}</strong><small>${item.text}</small></span><time>${item.updated.replaceAll(' / ', '/')}</time><span class="release-tag ${['red','blue','green','purple'][index]}">${['政策公告','流程更新','規範更新','教學資源'][index]}</span>${icon('chevron')}</button>`).join('')}</div>`, 'reference-card')}${card(`<div class="section-title stacked"><div><h2>常用文件</h2><span>精選常用的政策文件與作業指引，快速下載查閱。</span></div><button class="link-action">查看全部 ${icon('chevron')}</button></div><div class="document-list">${[['PDF','員工費用報銷管理辦法','PDF · 1.2 MB'],['PDF','國內出差旅費報支要點','PDF · 890 KB'],['DOC','付款申請作業指引','DOC · 560 KB'],['PDF','發票憑證審核標準','PDF · 1.1 MB'],['DOC','Helios 系統操作手冊（付款申請）','DOC · 2.3 MB']].map(([type,title,meta]) => `<button type="button" data-document="${title}"><span class="file-type ${type.toLowerCase()}">${type}</span><span><strong>${title}</strong><small>${meta}</small></span>${icon('upload')}</button>`).join('')}</div>`, 'reference-card')}</div>`;
  }
  function referenceTrackPage() {
    const applications = loadApplications();
    const filtered = applications.filter(item => (state.filter === '全部' || item.status === state.filter) && `${item.id} ${item.title} ${item.type}`.includes(state.search));
    return `${employeeBanner('我的申請', '隨時查詢申請進度，掌握每一筆申請的處理狀態。', '您可以查看申請詳情、處理進度與相關通知，如需補件也會在此顯示。')}
      <div class="track-status-grid">${[['進行中', 'blue', 'clock', '申請審核中'], ['已完成', 'green', 'check', '已完成處理'], ['需補件', 'orange', 'info', '待提供更多資料'], ['已取消', 'red', 'close', '已取消的申請']].map(([label, color, ico, text]) => `<button class="track-status ${color}" type="button" data-filter="${label}"><span class="status-icon">${icon(ico)}</span><span><strong>${label}</strong><b>${applications.filter(item => item.status === label).length} <small>件</small></b><small>${text}</small></span>${icon('chevron')}</button>`).join('')}</div>
      ${card(`<div class="track-filters"><span>申請狀態</span>${['全部', '進行中', '已完成', '需補件', '已取消'].map(label => `<button type="button" data-filter="${label}" class="filter ${state.filter === label ? 'selected' : ''}">${label}${label === '全部' ? ` (${applications.length})` : ''}</button>`).join('')}<label class="reference-search">${icon('search')}<input id="content-search" type="search" placeholder="搜尋申請編號、申請項目或目的..." value="${escapeHtml(state.search)}"></label><button class="outline-filter" type="button" data-advanced-filter>${icon('search')} 篩選條件</button></div>`, 'reference-card track-control')}
      ${card(`<div class="track-table-heading"><span>共 ${filtered.length} 筆申請記錄</span><label>排序： <select><option>申請日期（最新 → 最舊）</option><option>申請日期（最舊 → 最新）</option></select></label></div>${referenceApplicationTable(filtered.slice(state.listPage * 10, state.listPage * 10 + 10))}<div class="table-pagination"><span>顯示 ${filtered.length ? state.listPage * 10 + 1 : 0} - ${Math.min(filtered.length, state.listPage * 10 + 10)} / 共 ${filtered.length} 筆</span><div><button type="button" data-list-page="${Math.max(0, state.listPage - 1)}" aria-label="上一頁">‹</button>${Array.from({length: Math.max(1, Math.ceil(filtered.length / 10))}, (_, index) => `<button type="button" data-list-page="${index}" class="${state.listPage === index ? 'selected' : ''}">${index + 1}</button>`).join('')}<button type="button" data-list-page="${Math.min(Math.max(0, Math.ceil(filtered.length / 10) - 1), state.listPage + 1)}" aria-label="下一頁">›</button></div></div>`, 'reference-card track-table')}`;
  }
  function referenceServicePage() {
    const selected = services.find(item => item.id === state.selectedService);
    return `${employeeBanner('申請服務', '從常用服務選擇您的需求，快速開始財務申請。', '報銷、出差與付款申請皆為靜態示範流程。')}
      ${card(`<div class="section-title stacked"><div><h2>常用服務</h2><span>申請各項財務服務，提升工作效率</span></div></div>${referenceServiceTiles()}`, 'reference-card service-reference-section')}
      ${card(`<div class="service-guide"><span class="guide-icon">${icon('info')}</span><div><h2>員工先從首頁找到申請入口</h2><p>點選「報銷申請／出差申請／付款申請」後，在本展示中建立一筆示範申請。實際環境會導向 Helios 完成送件。</p></div></div>`, 'reference-card service-guide-card')}
      ${selected ? `<div class="modal-backdrop"><section class="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><div class="modal-head"><div><span class="eyebrow">DEMO APPLICATION</span><h2 id="modal-title">${selected.title}</h2></div><button class="icon-button" data-close-modal aria-label="關閉">${icon('close')}</button></div><p>${selected.description}</p><form id="application-form"><input type="hidden" name="service" value="${selected.id}"><label>申請主旨<input name="title" maxlength="60" required placeholder="請輸入示範申請主旨"></label><label>金額（新臺幣）<input name="amount" type="number" min="1" max="9999999" required placeholder="0"></label><label>說明<textarea name="description" maxlength="300" rows="3" placeholder="簡述申請內容（選填）"></textarea></label><div class="modal-note">${icon('info')}資料僅儲存在本機瀏覽器，不會送出至任何系統。</div><div class="modal-actions"><button type="button" class="button button-outline" data-close-modal>取消</button><button type="submit" class="button button-primary">建立示範申請 ${icon('arrow')}</button></div></form></section></div>` : ''}`;
  }
