'use strict';
  function shell(content) {
    const current = nav[state.role].find(item => item[0] === state.page);
    const name = 'Evren';
    const initials = 'E';
    const roleLabel = state.role === 'finance' ? 'Finance' : 'Employee';
    return `<div class="app-shell ${state.mobileOpen ? 'nav-open' : ''}">
      <aside class="sidebar" aria-label="主要導覽">
        <div class="brand"><span class="brand-mark"><i></i><i></i><i></i><i></i></span><strong>Finance SSC</strong></div>
        <nav class="side-nav">${nav[state.role].map(([page, label]) => `<button class="nav-item ${state.page === page ? 'active' : ''}" type="button" data-page="${page}" ${state.page === page ? 'aria-current="page"' : ''}>${icon(({ applications: 'track', service: 'review', faq: 'ask', reports: 'report', revenue: 'users', cash: 'clock', pnl: 'report', budget: 'track', bu: 'home', alerts: 'info' })[page] || page)}<strong>${label}</strong></button>`).join('')}</nav>
        <div class="sidebar-spacer"></div><button class="settings-link" type="button" data-settings>${icon('settings')}<span>個人設定</span></button>
      </aside>
      <div class="mobile-backdrop" data-close-menu></div>
      <div class="main-column">
        <header class="topbar"><div class="topbar-left"><button class="icon-button menu-button" type="button" data-menu aria-label="開啟選單">${icon('menu')}</button><span class="role-identity">${icon('users')} ${state.role === 'finance' ? '財務人員 Finance' : '一般員工 Employee'}</span></div><label class="global-search">${icon('search')}<input id="global-search" type="search" placeholder="${state.role === 'finance' ? '搜尋報表、BU、科目、關鍵字...' : '搜尋服務、政策、SOP 或任何問題...'}" aria-label="全站搜尋"></label><div class="topbar-actions"><button class="icon-button notification-button" type="button" data-notification aria-label="通知" aria-expanded="${state.notificationOpen}">${icon('bell')}<i>${state.role === 'finance' ? 6 : 3}</i></button><button class="icon-button help-button" type="button" data-page="${state.role === 'finance' ? 'reports' : 'faq'}" aria-label="說明">${icon('ask')}</button><span class="topbar-rule"></span><label class="profile-switch"><span class="header-avatar">${initials}</span><span class="profile-copy"><strong>${name}</strong><small>${roleLabel}</small></span><select id="role-switch" aria-label="切換角色"><option value="employee" ${state.role === 'employee' ? 'selected' : ''}>一般員工</option><option value="finance" ${state.role === 'finance' ? 'selected' : ''}>財務人員</option></select>${icon('chevron')}</label></div></header>
        ${state.notificationOpen ? `<div class="notification-popover">${icon('info')} 此為靜態展示，沒有即時通知。</div>` : ''}
        <main class="page-content" id="main-content">${content}</main>
      </div>
      ${state.toast ? `<div class="toast" role="status">${icon('check')}${escapeHtml(state.toast)}</div>` : ''}
    </div>`;
  }

  function caseTable(cases, withAction) {
    return `<div class="table-scroll"><table><thead><tr><th>申請編號</th><th>申請人／項目</th><th>送出日期</th><th>金額</th><th>狀態</th>${withAction ? '<th>操作</th>' : ''}</tr></thead><tbody>${cases.length ? cases.map(item => `<tr><td class="mono">${item.id}</td><td><strong>${item.title}</strong><small>${item.person} · ${item.type}</small></td><td>${item.date}</td><td>${item.amount}</td><td>${badge(item.status)}</td>${withAction ? `<td><button class="table-action" data-review="${item.id}">${item.status === '待審核' ? '標記處理中' : '檢視'}</button></td>` : ''}</tr>`).join('') : `<tr><td colspan="${withAction ? 6 : 5}" class="empty-state">目前沒有符合條件的案件。</td></tr>`}</tbody></table></div>`;
  }
  function reviewPage() {
    const cases = state.financeCases.filter(item => (state.filter === '全部' || item.status === state.filter) && `${item.id} ${item.title} ${item.person}`.includes(state.search));
    return `${pageTitle('APPLICATION REVIEW', '申請審核', '檢視示範案件並追蹤處理狀態。')}
      ${card(`<div class="card-heading"><div><h2>案件清單</h2><p>僅供互動展示，不會進行真正審核</p></div><span class="result-count">${cases.length} 筆案件</span></div><div class="toolbar"><label class="search-box">${icon('search')}<input id="content-search" type="search" placeholder="搜尋案件或申請人" value="${escapeHtml(state.search)}" aria-label="搜尋案件"></label><div class="filter-row compact">${['全部', '待審核', '處理中'].map(label => `<button class="filter ${state.filter === label ? 'selected' : ''}" data-filter="${label}">${label}</button>`).join('')}</div></div>${caseTable(cases, true)}`, 'table-card')}`;
  }
  function faqPage() {
    const visible = faqs.filter(item => `${item.q} ${item.a} ${item.tag}`.includes(state.search));
    return `${pageTitle('FAQ / AI ASSISTANT', '常見問題／AI 助理', '先找常見解答，或使用示範助理取得導覽建議。')}
      <div class="faq-layout"><section>${card(`<div class="card-heading"><div><h2>常見問題</h2><p>快速找到解答</p></div></div><label class="search-box full">${icon('search')}<input id="content-search" type="search" placeholder="搜尋常見問題" value="${escapeHtml(state.search)}" aria-label="搜尋常見問題"></label><div class="faq-list">${visible.length ? visible.map((item, index) => `<div class="faq-item"><button type="button" data-faq-index="${faqs.indexOf(item)}" aria-expanded="${state.faqOpen === faqs.indexOf(item)}"><span><small>${item.tag}</small><strong>${item.q}</strong></span><span class="faq-plus">${state.faqOpen === faqs.indexOf(item) ? '−' : '+'}</span></button>${state.faqOpen === faqs.indexOf(item) ? `<p>${item.a}</p>` : ''}</div>`).join('') : '<p class="empty-state">沒有找到符合的問題。</p>'}</div>`, 'faq-card')}</section><section>${card(`<div class="assistant-heading"><span class="assistant-mark">${icon('ask')}</span><div><h2>Finance SSC 助理</h2><p>示範導覽，不連接 AI 服務</p></div></div><div class="chat-messages" id="chat-messages"><div class="chat-message bot">您好！我可以協助您找到財務政策、申請服務與進度查詢入口。</div>${state.assistant.map(message => `<div class="chat-message user">${escapeHtml(message.user)}</div><div class="chat-message bot">${escapeHtml(message.reply)}</div>`).join('')}</div><div class="suggestions"><button data-suggestion="如何申請費用報銷？">費用報銷</button><button data-suggestion="如何追蹤申請？">申請進度</button></div><form id="assistant-form" class="chat-form"><input name="question" maxlength="120" required placeholder="輸入問題…" aria-label="輸入問題"><button type="submit" aria-label="送出問題">${icon('arrow')}</button></form>`, 'assistant-card')}</section></div>`;
  }
  function mountainArt(extra = '') { return `<div class="mountain-art ${extra}" aria-hidden="true"><span class="sun"></span><span class="mountain mountain-back one"></span><span class="mountain mountain-back two"></span><span class="mountain mountain-front one"></span><span class="mountain mountain-front two"></span><span class="mountain mountain-front three"></span></div>`; }
  function employeeBanner(title, lead, detail = '') { return `<section class="employee-banner"><div class="banner-copy"><h1>${title}</h1><p>${lead}</p>${detail ? `<small>${detail}</small>` : ''}</div>${mountainArt()}${title === '懂規定' ? `<svg class="banner-book" viewBox="0 0 225 140" aria-hidden="true"><defs><linearGradient id="bookBlue" x1="0" x2="1"><stop stop-color="#2280ff"/><stop offset="1" stop-color="#5ba4ff"/></linearGradient></defs><path d="M12 27Q60 15 112 39Q164 15 213 27v100q-54-14-101 12Q65 113 12 127z" fill="url(#bookBlue)" opacity=".94"/><path d="M27 16Q71 5 111 28v94Q70 101 27 112z" fill="#f8fbff" stroke="#98c3ff" stroke-width="3"/><path d="M197 16Q153 5 113 28v94q41-21 84-10z" fill="#f8fbff" stroke="#98c3ff" stroke-width="3"/><path d="M111 28v94" stroke="#80b7fb" stroke-width="3"/><path d="M42 39q26-4 55 10M42 57q26-4 55 10M42 75q26-4 55 10M127 48q27-13 55-9M127 66q27-13 55-9M127 84q27-13 55-9" fill="none" stroke="#c0d8fb" stroke-width="6" stroke-linecap="round"/></svg>` : ''}</section>`; }
  function referenceServiceTiles() { return `<div class="reference-service-grid">${[['expense', '報銷申請', '差旅／交際／日常費用', 'green'], ['travel', '出差申請', '國內／國外出差', 'blue'], ['payment', '付款申請', '廠商付款／其他付款', 'pink']].map(([id, title, desc, color]) => `<button class="reference-service ${color}" type="button" data-service="${id}"><span class="service-pictogram">${icon(id === 'travel' ? 'plane' : id === 'payment' ? 'credit' : 'receipt')}</span><strong>${title}</strong><small>${desc}</small><span class="powered">Powered by Helios ${icon('chevron')}</span></button>`).join('')}</div>`; }
  function referencePolicyTiles(items = [['報銷規範', '費用項目／憑證要求／核銷標準', 'green', 'receipt'], ['出差政策', '國內外出差申請／補助標準', 'blue', 'plane'], ['付款規範', '廠商付款／內部付款流程', 'orange', 'credit'], ['知識庫／操作教學', '常見問題／系統操作教學', 'purple', 'book']]) { return `<div class="reference-policy-grid">${items.map(([title, subtitle, color, ico]) => `<button class="reference-policy-tile" type="button" data-policy="${title}"><span class="tile-icon ${color}">${icon(ico)}</span><span><strong>${title}</strong><small>${subtitle}</small></span>${icon('chevron')}</button>`).join('')}</div>`; }
